spring:
  profiles:
    active: mysql
  application:
    name: headless
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

mybatis:
  mapper-locations: classpath:mappers/custom/*.xml,classpath*:/mappers/*.xml